version: '3'

services:

  artifactory:
    build:
      context: .
      dockerfile: .config/jfrog/Dockerfile
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"  # Add this line to expose port 8082
    networks:
      - jenkins_network
    volumes:
      - artifactory_data:/opt/artifactory/data

networks:
  jenkins_network:
    driver: bridge

volumes:
  artifactory_data:
